### ISSUE TITLE
Genius-TCAD-Open error: Assertion failure 

### ISSUE THREAD

**Issue by yoshiji-kobayashi** [cogenda/Genius-TCAD-Open#21]
HI!
I could install Genius-TCAD-Open to my system ubuntu12.04 without error.
But the program stopped and showed the following error message.
Error message: Assertion failure at ../../src/utlis/sync-file.cc:77
I use gcc-4.6.3 ,petsc-3.1-p8 ,cgnslib-2.5.2 and vtk-5.4.
Could you help me?

**Comment by yoshiji-kobayashi** [comment]
Hi!
After reinstallation of ubuntu12.04, I could install Genius-TCAD-Open and use it.
Petsc-3.1-p8 was compiled with OPTFLAGS="-O1". Using OPTFLAGS="-O2", C/C++ test erros occured. Thanks for Genius TCAD Open Source.

**Comment by gdiso** [comment]
please make sure you have the fully read/write permission for the working directory.

**Comment by yoshiji-kobayashi** [comment]
Dear Gong Ding
After I made sure the fully read/write permission for my working directory,
assertion failure diappeared.
Thank you for your advice.
I am sorry for too late reply.

Yoshiji Kobayashi
