### ISSUE TITLE
Genius-TCAD-Open build failed

### ISSUE THREAD

**Issue by ereztadmor** [cogenda/Genius-TCAD-Open#24]
Hello,
when trying to compile Genius on ubuntu I get the following error:

[309/605] cxx: src/parser/parser.cc -> build/default/src/parser/parser.cc.2.o
In file included from ../../src/parser/parser.cc:69:0:
/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/parser/input.y: In function ‘int InputYY::yyparse(void*)’:
/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/parser/input.y:91:10: error: expected ‘;’ before ‘}’ token
          }
          ^
Waf: Leaving directory `/home/ereztadmor/Downloads/Genius-TCAD-Open-master/build/default'
Build failed
 -> task failed (exit status 1): 
	{task 140442572740496: cxx parser.cc -> parser.cc.2.o}
['/usr/bin/g++-4.9', '-fPIC', '-fvisibility-inlines-hidden', '-O2', '-unroll', '-msse3', '-I/home/ereztadmor/Downloads/petsc-3.1-p8/linux-gnu-c-opt/include', '-I/home/ereztadmor/Downloads/petsc-3.1-p8/include', '', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/build/default/src/parser', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/build/default', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/base', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/bc', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/enums', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/fe', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/geom', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/hook', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/interpolation', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/material', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/math', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/math/TNT', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/mesh', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/meshgen', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/parser', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/partition', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/quadrature', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solution', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/ddm1', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/ddm1r', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/ddm2', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/ddm_ac', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/dg', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/doping_analytic', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/ebm3', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/emfem2d', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/hall', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/hdm', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/mix1', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/mixA1', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/mixA2', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/mixA3', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/mole_analytic', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/poisson', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/ray_tracing', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/solver/stress_solver', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/source', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/include/utils', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/ann', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/ann/ANN', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/csabathy', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/dfise', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/expreval', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/kdtree', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/klu', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/metis', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/mxml', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/nn', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/qshep', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/spice', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/spline', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/stanford', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/tif', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/tif3d', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/trex', '-I/home/ereztadmor/Downloads/Genius-TCAD-Open-master/src/contrib/triangle', '../../src/parser/parser.cc', '-c', '-o', 'src/parser/parser.cc.2.o']

Would appreciate assistance in solving this issue.

Best regards,
Erez

**Comment by gdiso** [comment]
Yes, it is a bug. Have already been fixed.
