### ISSUE TITLE
PETSC 3.5 error. libpetsc.so.3.5

### ISSUE THREAD

**Issue by keludso** [cogenda/Genius-TCAD-Open#25]
I have installed the necessary dependencies. PETSC-3.1 gcc-4.2 vtk-5.4.2 .  i have attached the config.log file along
[connfig.txt](https://github.com/cogenda/Genius-TCAD-Open/files/170855/connfig.txt)

I am facing the following error 
[513/620] cxx: src/solver/fvm_flex_pde_solver.cc -> build/default/src/solver/fvm_flex_pde_solver.cc.2.o
../../src/solver/fvm_flex_nonlinear_solver.cc: In member function ‘virtual void FVM_FlexNonlinearSolver::load_vector_petsc(_p_Vec*, const std::string&) const’:
../../src/solver/fvm_flex_nonlinear_solver.cc:359: error: cannot convert ‘_p_Vec*’ to ‘_p_PetscViewer*’ for argument ‘1’ to ‘PetscErrorCode VecLoad(_p_PetscViewer*, const char*, _p_Vec**)’
Waf: Leaving directory `/home/kelvin/Documents/Genius-TCAD-Open-master/build/default'
Build failed
 -> task failed (exit status 1): 
	{task 140382486222736: cxx fvm_flex_nonlinear_solver.cc -> fvm_flex_nonlinear_solver.cc.2.o}
['/usr/bin/g++', '-fPIC', '-pipe', '-fvisibility-inlines-hidden', '-O2', '-unroll', '-msse3', '-I/home/kelvin/Documents/petsc-3.1-p8/linux-gnu-c-opt/include', '-I/home/kelvin/Documents/petsc-3.1-p8/include/mpiuni', '-I/home/kelvin/Documents/petsc-3.1-p8/include', '', '-I/usr/local/include/vtk-5.4', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/build/default/src/parser', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/build/default', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/base', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/bc', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/enums', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/fe', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/geom', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/hook', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/interpolation', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/material', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/math', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/math/TNT', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/mesh', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/meshgen', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/parser', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/partition', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/quadrature', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solution', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/ddm1', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/ddm2', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/ddm_ac', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/dg', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/doping_analytic', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/ebm3', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/emfem2d', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/hall', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/mix1', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/mixA1', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/mixA2', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/mixA3', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/mole_analytic', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/poisson', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/ray_tracing', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/solver/stress_solver', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/source', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/include/utils', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/ann', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/ann/ANN', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/csabathy', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/dfise', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/expreval', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/kdtree', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/klu', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/metis', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/mxml', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/nn', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/qshep', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/spice', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/spline', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/stanford', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/tif3d', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/trex', '-I/home/kelvin/Documents/Genius-TCAD-Open-master/src/contrib/triangle', '../../src/solver/fvm_flex_nonlinear_solver.cc', '-c', '-o', 'src/solver/fvm_flex_nonlinear_solver.cc.2.o']

**Comment by gdiso** [comment]
The installation guide is out of date.
Genius always following the update of petsc, so please use petsc 3.5.  Petsc 3.6 works, but has not been fully tested.

**Comment by keludso** [comment]
Hey thanks . The installation worked great. 

Now when i am running a example file its giving the following error.error while loading shared libraries: libpetsc.so.3.5: cannot open shared object file: No such file or directory

**Comment by gdiso** [comment]
please set environment variable LD_LIBRARY_PATH point to the directory which contains the shared library file *.so. This is a common knowledge in LINUX system.

**Comment by keludso** [comment]
hey thanks...
